### ISSUE TITLE
logger.js 有警告

### ISSUE THREAD

**Issue by WindOfNet** [park1977/basic-node-template#1]
https://github.com/park1977/basic-node-template/blob/master/.eslintrc.json#L27
https://github.com/park1977/basic-node-template/blob/master/logger.js#L15

```json
  "rules": {
    "array-element-newline": [
      "warn",
      {
        "multiline": true,
        "minItems": 3
      }
    ]
  }
```

.eslint 設定導致在 logger.js template 會有一個警告，這是預期的嗎？  
![image](https://github.com/park1977/basic-node-template/assets/13547942/ad94e0fc-a9f6-468b-931e-d94f420a9c20)

**Comment by park1977** [comment]
預期的, 看你要不要改, 我是覺得可有可無, 所以設定為warning
